remove un-needed workflow steps due to self hosted runner & fix archives page routing

diff --git a/.github/workflows/deploy-main.yaml b/.github/workflows/deploy-main.yaml
--- a/.github/workflows/deploy-main.yaml
+++ b/.github/workflows/deploy-main.yaml
@@ -46,32 +46,32 @@ jobs:
           directory: "dist/"
           arguments: --disable-external --checks --allow-hash-href --ignore_urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"
 
-      - name: Get Public IP
-        id: ip
-        uses: candidob/get-runner-ip@v1.0.0
+      # - name: Get Public IP
+      #   id: ip
+      #   uses: candidob/get-runner-ip@v1.0.0
 
-      - name: Setup Linode CLI
-        uses: linode/action-linode-cli@v1
-        with:
-          token: "${{ secrets.LINODE_CLI_TOKEN }}"
+      # - name: Setup Linode CLI
+      #   uses: linode/action-linode-cli@v1
+      #   with:
+      #     token: "${{ secrets.LINODE_CLI_TOKEN }}"
 
-      - name: Setup SSH
-        id: ssh-setup
-        run: |
-          echo ${{ secrets.LINODEFINGERPRINT }} >> ~/.ssh/known_hosts
+      # - name: Setup SSH
+      #   id: ssh-setup
+      #   run: |
+      #     echo ${{ secrets.LINODEFINGERPRINT }} >> ~/.ssh/known_hosts
 
-      - name: Get Linode Script
-        run: |
-          wget https://raw.githubusercontent.com/alexandzors/utils/refs/heads/main/linode-scripts/linode.sh
+      # - name: Get Linode Script
+      #   run: |
+      #     wget https://raw.githubusercontent.com/alexandzors/utils/refs/heads/main/linode-scripts/linode.sh
 
-      - name: Open Linode Cloud Firewall
-        if: (steps.ssh-setup.outcome  == 'success')
-        env:
-          PUB_IP: "${{ steps.ip.outputs.ipv4 }}/32"
-          HOME_IP: "${{ secrets.HOMEIP }}"
-          LINODE_FW_ID: "${{ secrets.LINODE_FW_ID }}"
-        run: |
-          bash ./linode.sh -a
+      # - name: Open Linode Cloud Firewall
+      #   if: (steps.ssh-setup.outcome  == 'success')
+      #   env:
+      #     PUB_IP: "${{ steps.ip.outputs.ipv4 }}/32"
+      #     HOME_IP: "${{ secrets.HOMEIP }}"
+      #     LINODE_FW_ID: "${{ secrets.LINODE_FW_ID }}"
+      #   run: |
+      #     bash ./linode.sh -a
 
       - name: Deploy
         uses: burnett01/rsync-deployments@7.0.2
@@ -84,10 +84,10 @@ jobs:
           remote_user: ${{ secrets.LINODEUSER }}
           remote_key: ${{ secrets.LINODESSHKEY }}
 
-      - name: Close Linode Cloud Firewall
-        if: (steps.deploy.outcome  == 'success') || (steps.deploy.outcome  == 'failed' || steps.deploy.outcome  == 'skipped')
-        run: |
-          bash ./linode.sh -d
+      # - name: Close Linode Cloud Firewall
+      #   if: (steps.deploy.outcome  == 'success') || (steps.deploy.outcome  == 'failed' || steps.deploy.outcome  == 'skipped')
+      #   run: |
+      #     bash ./linode.sh -d
 
       - name: Purge Cloudflare Cache
         if: (steps.deploy.outcome  == 'success')
